---
title: "Academic Blog"
---

<h2><span class="fa fa-file-text-o" aria-hidden="true"></span> Posts</h2> 
<hr>

<!-- 2018 March Madness -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Simulating-2018-NCAA-March-Madness-Tournament-Performance-in-R.html" class="postLink"> Simulating 2018 NCAA March Madness Tournament Performance in R</a></h3>

<span class="glyphicon glyphicon-time"></span> March 20, 2018
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>

A few of us graduate students decided it would be fun to simulate this year's NCAA Men's National Championship tournament using R. When we all met to discuss our method to simuluate tournament performance, we quickly realized several methods emerged...

<br>

<!-- Lit Review -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Writing-a-Literature-Review.html" class="postLink"> Writing a Literature Review</a></h3>

<span class="glyphicon glyphicon-time"></span> September 25, 2017
<span class="label label-primary">Academic</span>

I recently completed my first comprehensive literature review as part of a graduate school milestone project. Before starting, I sought guidance from online blogs and university workshops held by our library. The tips I learned from these resources were extremely helpful, but not everything worked for me. This is simply a list of things that worked/did not work for me during the reading and writing process of my literature review...

<br>
